# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLostTimeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalesDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Line', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('7', '7'), ('8', '8'), ('9', '9'), ('SPONGE', 'SPONGE'), (None, None)], max_length=100, null=True)),
                ('Shift', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), (None, None)], max_length=100, null=True)),
                ('OracleType', models.CharField(blank=True, max_length=100, null=True)),
                ('MIPS_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('LostTimeMinutes', models.FloatField(blank=True, null=True)),
                ('LostTimeValue', models.FloatField(blank=True, null=True)),
                ('Occ', models.FloatField(blank=True, null=True)),
                ('OracleCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('Cause', models.CharField(blank=True, max_length=100, null=True)),
                ('Comments', models.CharField(blank=True, max_length=100, null=True)),
                ('LineStop', models.CharField(blank=True, max_length=100, null=True)),
                ('Init', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTimeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalesDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Line', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('7', '7'), ('8', '8'), ('9', '9'), ('SPONGE', 'SPONGE'), (None, None)], max_length=100, null=True)),
                ('Shift', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), (None, None)], max_length=100, null=True)),
                ('OracleType', models.CharField(blank=True, max_length=100, null=True)),
                ('OracleFormula', models.CharField(blank=True, max_length=100, null=True)),
                ('MIPS_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('SchedChangeOverTime_min', models.FloatField(blank=True, null=True)),
                ('OracleTheoChangeOverTime_min', models.FloatField(blank=True, null=True)),
                ('ActualChangeOverTime_min', models.FloatField(blank=True, null=True)),
                ('Init', models.CharField(blank=True, max_length=100, null=True)),
                ('WrappingStartDateTime', models.CharField(blank=True, max_length=100, null=True)),
                ('WrappingEndDateTime', models.CharField(blank=True, max_length=100, null=True)),
                ('MechLostTime_min', models.FloatField(blank=True, null=True)),
                ('SchedLostTime_min', models.FloatField(blank=True, null=True)),
                ('AOLostTime_min', models.FloatField(blank=True, null=True)),
                ('ActualRunTime_min', models.FloatField(blank=True, null=True)),
                ('TotalLostTime_min', models.FloatField(blank=True, null=True)),
                ('OracleAOLostTime_min', models.FloatField(blank=True, null=True)),
                ('TheoRunTime_min', models.FloatField(blank=True, null=True)),
                ('EngTheoRunTime_min', models.FloatField(blank=True, null=True)),
                ('TimeVar_min', models.FloatField(blank=True, null=True)),
                ('TimeVar_perc', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
