# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('7', '7'), ('8', '8'), ('9', '9'), ('SPONGE', 'SPONGE'), (None, None)], max_length=30, null=True)),
                ('AOR_type', models.CharField(blank=True, choices=[('major', 'major'), ('minor', 'minor')], max_length=30, null=True)),
                ('equip_name', models.CharField(max_length=100)),
                ('equip_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.FileField(upload_to='WorkSchedule/WorkConfig/excel')),
                ('file_type', models.CharField(blank=True, choices=[('Tasks', 'Tasks'), ('WorkerAvail', 'WorkerAvail'), ('AOR', 'AOR'), ('Company', 'Company'), ('Equipment', 'Equipment'), ('PMs', 'WorkerAvail'), ('SomaxAccount', 'SomaxAccount'), ('Worker', 'Worker')], max_length=30, null=True)),
                ('processor', models.CharField(blank=True, choices=[('TasksLoadProcessor', 'TasksLoadProcessor'), ('WorkerAvailLoadProcessor', 'WorkerAvailLoadProcessor'), ('AORLoadProcessor', 'AORLoadProcessor'), ('CompanyLoadProcessor', 'CompanyLoadProcessor'), ('EquipmentLoadProcessor', 'EquipmentLoadProcessor'), ('PMsLoadProcessor', 'PMsLoadProcessor'), ('SomaxAccountLoadProcessor', 'SomaxAccountLoadProcessor'), ('WorkerLoadProcessor', 'WorkerLoadProcessor')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('loaded', 'loaded')], default='new', max_length=30)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='WorkConfig', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('equipment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('line', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_name_clean', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SomaxAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('security_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('lead', 'lead'), ('worker', 'worker')], default='lead', max_length=30)),
                ('shift', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), (None, None)], default='1', max_length=30)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=30)),
                ('type', models.CharField(choices=[('employee', 'employee'), ('contractor', 'contractor'), ('none', 'none')], default='employee', max_length=30)),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.CASCADE, to='WorkConfig.Company', to_field='business_name')),
                ('somax_account', models.ForeignKey(blank=True, db_column='somax_account', null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkConfig.SomaxAccount', to_field='user_name')),
            ],
        ),
        migrations.AddField(
            model_name='aor',
            name='equip_id',
            field=models.ForeignKey(blank=True, db_column='equipment_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkConfig.Equipment'),
        ),
        migrations.AddField(
            model_name='aor',
            name='worker',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='WorkConfig.Workers', to_field='name'),
        ),
    ]
