# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 00:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WorkConfig', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterjob_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('PMs_type', models.CharField(blank=True, max_length=100, null=True)),
                ('due_days', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('work_type', models.CharField(blank=True, choices=[('CM', 'CM'), ('PM', 'PM'), ('EV', 'EV'), ('EM', 'EM'), (None, None)], max_length=10, null=True)),
                ('current_status', models.CharField(choices=[('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Complete', 'Complete'), ('Denied', 'Denied'), ('Scheduled', 'Scheduled'), ('Work Request', 'Work Request'), ('Wait For Parts', 'Wait For Parts')], default='Work Request', max_length=30)),
                ('line', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('7', '7'), ('8', '8'), ('9', '9'), ('SPONGE', 'SPONGE'), (None, None)], max_length=10, null=True)),
                ('shift', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), (None, None)], max_length=10, null=True)),
                ('priority', models.CharField(blank=True, choices=[('s', 's'), ('u', 'u'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('T', 'T'), ('O', 'O'), (None, None)], max_length=10, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('current_status_somax', models.CharField(choices=[('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Complete', 'Complete'), ('Denied', 'Denied'), ('Scheduled', 'Scheduled'), ('Work Request', 'Work Request'), ('Wait For Parts', 'Wait For Parts')], default='Work Request', max_length=30)),
                ('schedule_date_somax', models.DateTimeField(blank=True, null=True)),
                ('actual_date_somax', models.DateTimeField(blank=True, null=True)),
                ('estimate_hour', models.DurationField(default=datetime.timedelta(0))),
                ('scheduled_hour', models.DurationField(default=datetime.timedelta(0))),
                ('actual_hour', models.DurationField(default=datetime.timedelta(0))),
                ('parts_location', models.CharField(blank=True, max_length=100, null=True)),
                ('fail_code', models.CharField(blank=True, max_length=100, null=True)),
                ('completion_comments', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('file', 'file'), ('somax', 'somax'), ('auto', 'auto')], default='manual', max_length=100)),
                ('sync_to_somax', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('error', 'error')], max_length=20, null=True)),
                ('AOR', models.ForeignKey(blank=True, db_column='AOR', null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkConfig.AOR')),
                ('PMs', models.ForeignKey(blank=True, db_column='PMs', null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkTasks.PMs')),
                ('assigned', models.ForeignKey(blank=True, db_column='assigned', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tasks_assigned', to='WorkConfig.SomaxAccount')),
                ('created_by', models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, db_column='creator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tasks_creator', to='WorkConfig.SomaxAccount')),
                ('document', models.ForeignKey(blank=True, db_column='document', null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkConfig.Documents', to_field='name')),
                ('equipment', models.ForeignKey(blank=True, db_column='equipment', null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkConfig.Equipment')),
            ],
        ),
    ]
